### ISSUE TITLE
bulk list

### ISSUE THREAD

**Issue by LeninZapata** [jordon31/OF-SCR#3]
Is there not a way with an option to go through the subscribed list and download the new content? I say this because I have 20 subscriptions and I have to download it one by one

**Comment by jordon31** [comment]
Hello.. for bulk downloading, just select the option "*** Download All Models ***" and it will do everything automatically.

If you indent something else, I didn't understand.

**Comment by LeninZapata** [comment]
I had not set that option, I'm going to try it, thank you very much!

**Comment by LeninZapata** [comment]
Some time ago, I put this problem in another Fork, could you add the date of each photo? I would like to know that this photo is X user, on X date, I notice it is more organized.

{id}-{date}-{user}.{ext}

https://github.com/k0rnh0li0/onlyfans-dl/issues/147

**Comment by jordon31** [comment]
Mhh.. I don't like the idea because it's not visually appealing.. for the dates, you just need to right-click and select "Group by --> Date Modified" to see the details of the post's time and day it was published.

I did everything I could to make the folders as clean as possible based on years -- weeks -- days and yesterday.

**Comment by LeninZapata** [comment]
I understand, very well, if I have any other suggestions I will let you know. Thank you so much.
